display_name: Substore Assistant
package_name: substoreAssistant
maintainer:
  name: KaringX
priority: optional
section: x11
installed_size: 6604
essential: false
icon: assets/images/app_icon_256.png

dependencies:
  - libgtk-3-0
  - libayatana-appindicator3-1
#  - libcurl4t64 
#  - libglib2.0-dev
#  - libjpeg-turbo8
  - libkeybinder-3.0-0
  - libsecret-1-0
  - libstdc++6
keywords:
  - Substore Assistant

generic_name: Substore Assistant

categories:
  - Network

startup_notify: true