script_template: inno_setup.iss
app_id: 74F1C307-2E21-4951-BB25-763C3A2AE9EF
app_name: Substore Assistant
display_name: Substore Assistant
executable_name: substoreAssistant.exe
publisher_name: Supernova Nebula LLC
publisher_url: https://clashmi.app
create_desktop_icon: true
setup_icon_file: windows/runner/resources/app_icon.ico